# This is a basic workflow to help you get started with Actions

name: CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run tests
        run: |
          make test
      - name: Check coverage
        run: |
          make test-coverage
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 15b3522d7738e5333d58887a97df6158c75ba4e61d54c938f440b386e7ebcd0f
